CREATE TABLE `tasks` (
  `id` INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(255)  NOT NULL  DEFAULT ''  COMMENT '任务名称',
  `priority` INT(10)  NOT NULL  DEFAULT 0  COMMENT '任务优先级',
  `done` INT(2)  NOT NULL  DEFAULT 0  COMMENT '是否完成',
  `is_parent` INT(2)  NOT NULL  DEFAULT 1  COMMENT '是否是根任务'
  `group_id` INT(11) UNSIGNED  DEFAULT NULL COMMENT '所属任务组'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='任务详情';

CREATE TABLE `group` (
  `id` INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(255)  NOT NULL  DEFAULT ''  COMMENT '名称'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='任务组';
